/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package kinect;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class link_msg_t implements lcm.lcm.LCMEncodable
{
    public int joint_id;
    public kinect.point3d_t source;
    public kinect.point3d_t dest;
 
    public link_msg_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe071115012961010L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(kinect.link_msg_t.class))
            return 0L;
 
        classes.add(kinect.link_msg_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + kinect.point3d_t._hashRecursive(classes)
             + kinect.point3d_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.joint_id); 
 
        this.source._encodeRecursive(outs); 
 
        this.dest._encodeRecursive(outs); 
 
    }
 
    public link_msg_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public link_msg_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static kinect.link_msg_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        kinect.link_msg_t o = new kinect.link_msg_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.joint_id = ins.readInt();
 
        this.source = kinect.point3d_t._decodeRecursiveFactory(ins);
 
        this.dest = kinect.point3d_t._decodeRecursiveFactory(ins);
 
    }
 
    public kinect.link_msg_t copy()
    {
        kinect.link_msg_t outobj = new kinect.link_msg_t();
        outobj.joint_id = this.joint_id;
 
        outobj.source = this.source.copy();
 
        outobj.dest = this.dest.copy();
 
        return outobj;
    }
 
}

