/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package kinect;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class projected_point2d_t implements lcm.lcm.LCMEncodable
{
    public float u;
    public float v;
 
    public projected_point2d_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x7f2d87baacd686d7L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(kinect.projected_point2d_t.class))
            return 0L;
 
        classes.add(kinect.projected_point2d_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.u); 
 
        outs.writeFloat(this.v); 
 
    }
 
    public projected_point2d_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public projected_point2d_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static kinect.projected_point2d_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        kinect.projected_point2d_t o = new kinect.projected_point2d_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.u = ins.readFloat();
 
        this.v = ins.readFloat();
 
    }
 
    public kinect.projected_point2d_t copy()
    {
        kinect.projected_point2d_t outobj = new kinect.projected_point2d_t();
        outobj.u = this.u;
 
        outobj.v = this.v;
 
        return outobj;
    }
 
}

