/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package kinect;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class skeleton_msg_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int num_links;
    public int user_id;
    public kinect.link_msg_t links[];
 
    public skeleton_msg_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8196d52e0f1e466aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(kinect.skeleton_msg_t.class))
            return 0L;
 
        classes.add(kinect.skeleton_msg_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + kinect.link_msg_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.num_links); 
 
        outs.writeInt(this.user_id); 
 
        for (int a = 0; a < this.num_links; a++) {
            this.links[a]._encodeRecursive(outs); 
        }
 
    }
 
    public skeleton_msg_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public skeleton_msg_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static kinect.skeleton_msg_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        kinect.skeleton_msg_t o = new kinect.skeleton_msg_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.num_links = ins.readInt();
 
        this.user_id = ins.readInt();
 
        this.links = new kinect.link_msg_t[(int) num_links];
        for (int a = 0; a < this.num_links; a++) {
            this.links[a] = kinect.link_msg_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public kinect.skeleton_msg_t copy()
    {
        kinect.skeleton_msg_t outobj = new kinect.skeleton_msg_t();
        outobj.utime = this.utime;
 
        outobj.num_links = this.num_links;
 
        outobj.user_id = this.user_id;
 
        outobj.links = new kinect.link_msg_t[(int) num_links];
        for (int a = 0; a < this.num_links; a++) {
            outobj.links[a] = this.links[a].copy();
        }
 
        return outobj;
    }
 
}

