"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import kinect.projected_point2d_t

class segmentlist_t(object):
    __slots__ = ["timestamp", "left_normalized_line", "right_normalized_line", "left_normal", "right_normal"]

    def __init__(self):
        self.timestamp = 0
        self.left_normalized_line = [ kinect.projected_point2d_t() for dim0 in range(2) ]
        self.right_normalized_line = [ kinect.projected_point2d_t() for dim0 in range(2) ]
        self.left_normal = kinect.projected_point2d_t()
        self.right_normal = kinect.projected_point2d_t()

    def encode(self):
        buf = BytesIO()
        buf.write(segmentlist_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        for i0 in range(2):
            assert self.left_normalized_line[i0]._get_packed_fingerprint() == kinect.projected_point2d_t._get_packed_fingerprint()
            self.left_normalized_line[i0]._encode_one(buf)
        for i0 in range(2):
            assert self.right_normalized_line[i0]._get_packed_fingerprint() == kinect.projected_point2d_t._get_packed_fingerprint()
            self.right_normalized_line[i0]._encode_one(buf)
        assert self.left_normal._get_packed_fingerprint() == kinect.projected_point2d_t._get_packed_fingerprint()
        self.left_normal._encode_one(buf)
        assert self.right_normal._get_packed_fingerprint() == kinect.projected_point2d_t._get_packed_fingerprint()
        self.right_normal._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != segmentlist_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return segmentlist_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = segmentlist_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.left_normalized_line = []
        for i0 in range(2):
            self.left_normalized_line.append(kinect.projected_point2d_t._decode_one(buf))
        self.right_normalized_line = []
        for i0 in range(2):
            self.right_normalized_line.append(kinect.projected_point2d_t._decode_one(buf))
        self.left_normal = kinect.projected_point2d_t._decode_one(buf)
        self.right_normal = kinect.projected_point2d_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if segmentlist_t in parents: return 0
        newparents = parents + [segmentlist_t]
        tmphash = (0x48082176126ad5f3+ kinect.projected_point2d_t._get_hash_recursive(newparents)+ kinect.projected_point2d_t._get_hash_recursive(newparents)+ kinect.projected_point2d_t._get_hash_recursive(newparents)+ kinect.projected_point2d_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if segmentlist_t._packed_fingerprint is None:
            segmentlist_t._packed_fingerprint = struct.pack(">Q", segmentlist_t._get_hash_recursive([]))
        return segmentlist_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

