"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import kinect.link_msg_t

class skeleton_msg_t(object):
    __slots__ = ["utime", "num_links", "user_id", "links"]

    def __init__(self):
        self.utime = 0
        self.num_links = 0
        self.user_id = 0
        self.links = []

    def encode(self):
        buf = BytesIO()
        buf.write(skeleton_msg_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qii", self.utime, self.num_links, self.user_id))
        for i0 in range(self.num_links):
            assert self.links[i0]._get_packed_fingerprint() == kinect.link_msg_t._get_packed_fingerprint()
            self.links[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != skeleton_msg_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return skeleton_msg_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = skeleton_msg_t()
        self.utime, self.num_links, self.user_id = struct.unpack(">qii", buf.read(16))
        self.links = []
        for i0 in range(self.num_links):
            self.links.append(kinect.link_msg_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if skeleton_msg_t in parents: return 0
        newparents = parents + [skeleton_msg_t]
        tmphash = (0x8196d52e0f1e466a+ kinect.link_msg_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if skeleton_msg_t._packed_fingerprint is None:
            skeleton_msg_t._packed_fingerprint = struct.pack(">Q", skeleton_msg_t._get_hash_recursive([]))
        return skeleton_msg_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

