// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcmtypes/kinect_depth_msg_t.h"

static int __kinect_depth_msg_t_hash_computed;
static uint64_t __kinect_depth_msg_t_hash;

uint64_t __kinect_depth_msg_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __kinect_depth_msg_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__kinect_depth_msg_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x2006d888ce0bb5f6LL
         + __int64_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __byte_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __kinect_depth_msg_t_get_hash(void)
{
    if (!__kinect_depth_msg_t_hash_computed) {
        __kinect_depth_msg_t_hash = (int64_t)__kinect_depth_msg_t_hash_recursive(NULL);
        __kinect_depth_msg_t_hash_computed = 1;
    }

    return __kinect_depth_msg_t_hash;
}

int __kinect_depth_msg_t_encode_array(void *buf, int offset, int maxlen, const kinect_depth_msg_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].depth_data_nbytes), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, p[element].depth_data, p[element].depth_data_nbytes);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].depth_data_format), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].compression), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].uncompressed_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int kinect_depth_msg_t_encode(void *buf, int offset, int maxlen, const kinect_depth_msg_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __kinect_depth_msg_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __kinect_depth_msg_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __kinect_depth_msg_t_encoded_array_size(const kinect_depth_msg_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __int16_t_encoded_array_size(&(p[element].width), 1);

        size += __int16_t_encoded_array_size(&(p[element].height), 1);

        size += __int32_t_encoded_array_size(&(p[element].depth_data_nbytes), 1);

        size += __byte_encoded_array_size(p[element].depth_data, p[element].depth_data_nbytes);

        size += __int8_t_encoded_array_size(&(p[element].depth_data_format), 1);

        size += __int8_t_encoded_array_size(&(p[element].compression), 1);

        size += __int32_t_encoded_array_size(&(p[element].uncompressed_size), 1);

    }
    return size;
}

int kinect_depth_msg_t_encoded_size(const kinect_depth_msg_t *p)
{
    return 8 + __kinect_depth_msg_t_encoded_array_size(p, 1);
}

int __kinect_depth_msg_t_decode_array(const void *buf, int offset, int maxlen, kinect_depth_msg_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].depth_data_nbytes), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].depth_data = (uint8_t*) lcm_malloc(sizeof(uint8_t) * p[element].depth_data_nbytes);
        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, p[element].depth_data, p[element].depth_data_nbytes);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].depth_data_format), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].compression), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].uncompressed_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __kinect_depth_msg_t_decode_array_cleanup(kinect_depth_msg_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __int16_t_decode_array_cleanup(&(p[element].width), 1);

        __int16_t_decode_array_cleanup(&(p[element].height), 1);

        __int32_t_decode_array_cleanup(&(p[element].depth_data_nbytes), 1);

        __byte_decode_array_cleanup(p[element].depth_data, p[element].depth_data_nbytes);
        if (p[element].depth_data) free(p[element].depth_data);

        __int8_t_decode_array_cleanup(&(p[element].depth_data_format), 1);

        __int8_t_decode_array_cleanup(&(p[element].compression), 1);

        __int32_t_decode_array_cleanup(&(p[element].uncompressed_size), 1);

    }
    return 0;
}

int kinect_depth_msg_t_decode(const void *buf, int offset, int maxlen, kinect_depth_msg_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __kinect_depth_msg_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __kinect_depth_msg_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int kinect_depth_msg_t_decode_cleanup(kinect_depth_msg_t *p)
{
    return __kinect_depth_msg_t_decode_array_cleanup(p, 1);
}

int __kinect_depth_msg_t_clone_array(const kinect_depth_msg_t *p, kinect_depth_msg_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __int16_t_clone_array(&(p[element].width), &(q[element].width), 1);

        __int16_t_clone_array(&(p[element].height), &(q[element].height), 1);

        __int32_t_clone_array(&(p[element].depth_data_nbytes), &(q[element].depth_data_nbytes), 1);

        q[element].depth_data = (uint8_t*) lcm_malloc(sizeof(uint8_t) * q[element].depth_data_nbytes);
        __byte_clone_array(p[element].depth_data, q[element].depth_data, p[element].depth_data_nbytes);

        __int8_t_clone_array(&(p[element].depth_data_format), &(q[element].depth_data_format), 1);

        __int8_t_clone_array(&(p[element].compression), &(q[element].compression), 1);

        __int32_t_clone_array(&(p[element].uncompressed_size), &(q[element].uncompressed_size), 1);

    }
    return 0;
}

kinect_depth_msg_t *kinect_depth_msg_t_copy(const kinect_depth_msg_t *p)
{
    kinect_depth_msg_t *q = (kinect_depth_msg_t*) malloc(sizeof(kinect_depth_msg_t));
    __kinect_depth_msg_t_clone_array(p, q, 1);
    return q;
}

void kinect_depth_msg_t_destroy(kinect_depth_msg_t *p)
{
    __kinect_depth_msg_t_decode_array_cleanup(p, 1);
    free(p);
}

int kinect_depth_msg_t_publish(lcm_t *lc, const char *channel, const kinect_depth_msg_t *p)
{
      int max_data_size = kinect_depth_msg_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = kinect_depth_msg_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _kinect_depth_msg_t_subscription_t {
    kinect_depth_msg_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void kinect_depth_msg_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    kinect_depth_msg_t p;
    memset(&p, 0, sizeof(kinect_depth_msg_t));
    status = kinect_depth_msg_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding kinect_depth_msg_t!!!\n", status);
        return;
    }

    kinect_depth_msg_t_subscription_t *h = (kinect_depth_msg_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    kinect_depth_msg_t_decode_cleanup (&p);
}

kinect_depth_msg_t_subscription_t* kinect_depth_msg_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    kinect_depth_msg_t_handler_t f, void *userdata)
{
    kinect_depth_msg_t_subscription_t *n = (kinect_depth_msg_t_subscription_t*)
                       malloc(sizeof(kinect_depth_msg_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 kinect_depth_msg_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg kinect_depth_msg_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int kinect_depth_msg_t_subscription_set_queue_capacity (kinect_depth_msg_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int kinect_depth_msg_t_unsubscribe(lcm_t *lcm, kinect_depth_msg_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe kinect_depth_msg_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

