// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcmtypes/kinect_pointcloud_t.h"

static int __kinect_pointcloud_t_hash_computed;
static uint64_t __kinect_pointcloud_t_hash;

uint64_t __kinect_pointcloud_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __kinect_pointcloud_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__kinect_pointcloud_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x4b80c1a0b287166eLL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __kinect_pointcloud_t_get_hash(void)
{
    if (!__kinect_pointcloud_t_hash_computed) {
        __kinect_pointcloud_t_hash = (int64_t)__kinect_pointcloud_t_hash_recursive(NULL);
        __kinect_pointcloud_t_hash_computed = 1;
    }

    return __kinect_pointcloud_t_hash;
}

int __kinect_pointcloud_t_encode_array(void *buf, int offset, int maxlen, const kinect_pointcloud_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].x, p[element].num);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].y, p[element].num);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].z, p[element].num);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int kinect_pointcloud_t_encode(void *buf, int offset, int maxlen, const kinect_pointcloud_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __kinect_pointcloud_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __kinect_pointcloud_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __kinect_pointcloud_t_encoded_array_size(const kinect_pointcloud_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __int32_t_encoded_array_size(&(p[element].num), 1);

        size += __float_encoded_array_size(p[element].x, p[element].num);

        size += __float_encoded_array_size(p[element].y, p[element].num);

        size += __float_encoded_array_size(p[element].z, p[element].num);

    }
    return size;
}

int kinect_pointcloud_t_encoded_size(const kinect_pointcloud_t *p)
{
    return 8 + __kinect_pointcloud_t_encoded_array_size(p, 1);
}

int __kinect_pointcloud_t_decode_array(const void *buf, int offset, int maxlen, kinect_pointcloud_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].x = (float*) lcm_malloc(sizeof(float) * p[element].num);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].x, p[element].num);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].y = (float*) lcm_malloc(sizeof(float) * p[element].num);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].y, p[element].num);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].z = (float*) lcm_malloc(sizeof(float) * p[element].num);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].z, p[element].num);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __kinect_pointcloud_t_decode_array_cleanup(kinect_pointcloud_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __int32_t_decode_array_cleanup(&(p[element].num), 1);

        __float_decode_array_cleanup(p[element].x, p[element].num);
        if (p[element].x) free(p[element].x);

        __float_decode_array_cleanup(p[element].y, p[element].num);
        if (p[element].y) free(p[element].y);

        __float_decode_array_cleanup(p[element].z, p[element].num);
        if (p[element].z) free(p[element].z);

    }
    return 0;
}

int kinect_pointcloud_t_decode(const void *buf, int offset, int maxlen, kinect_pointcloud_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __kinect_pointcloud_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __kinect_pointcloud_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int kinect_pointcloud_t_decode_cleanup(kinect_pointcloud_t *p)
{
    return __kinect_pointcloud_t_decode_array_cleanup(p, 1);
}

int __kinect_pointcloud_t_clone_array(const kinect_pointcloud_t *p, kinect_pointcloud_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __int32_t_clone_array(&(p[element].num), &(q[element].num), 1);

        q[element].x = (float*) lcm_malloc(sizeof(float) * q[element].num);
        __float_clone_array(p[element].x, q[element].x, p[element].num);

        q[element].y = (float*) lcm_malloc(sizeof(float) * q[element].num);
        __float_clone_array(p[element].y, q[element].y, p[element].num);

        q[element].z = (float*) lcm_malloc(sizeof(float) * q[element].num);
        __float_clone_array(p[element].z, q[element].z, p[element].num);

    }
    return 0;
}

kinect_pointcloud_t *kinect_pointcloud_t_copy(const kinect_pointcloud_t *p)
{
    kinect_pointcloud_t *q = (kinect_pointcloud_t*) malloc(sizeof(kinect_pointcloud_t));
    __kinect_pointcloud_t_clone_array(p, q, 1);
    return q;
}

void kinect_pointcloud_t_destroy(kinect_pointcloud_t *p)
{
    __kinect_pointcloud_t_decode_array_cleanup(p, 1);
    free(p);
}

int kinect_pointcloud_t_publish(lcm_t *lc, const char *channel, const kinect_pointcloud_t *p)
{
      int max_data_size = kinect_pointcloud_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = kinect_pointcloud_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _kinect_pointcloud_t_subscription_t {
    kinect_pointcloud_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void kinect_pointcloud_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    kinect_pointcloud_t p;
    memset(&p, 0, sizeof(kinect_pointcloud_t));
    status = kinect_pointcloud_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding kinect_pointcloud_t!!!\n", status);
        return;
    }

    kinect_pointcloud_t_subscription_t *h = (kinect_pointcloud_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    kinect_pointcloud_t_decode_cleanup (&p);
}

kinect_pointcloud_t_subscription_t* kinect_pointcloud_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    kinect_pointcloud_t_handler_t f, void *userdata)
{
    kinect_pointcloud_t_subscription_t *n = (kinect_pointcloud_t_subscription_t*)
                       malloc(sizeof(kinect_pointcloud_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 kinect_pointcloud_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg kinect_pointcloud_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int kinect_pointcloud_t_subscription_set_queue_capacity (kinect_pointcloud_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int kinect_pointcloud_t_unsubscribe(lcm_t *lcm, kinect_pointcloud_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe kinect_pointcloud_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

