// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcmtypes/obstacle_haptic_array_t.h"

static int __obstacle_haptic_array_t_hash_computed;
static uint64_t __obstacle_haptic_array_t_hash;

uint64_t __obstacle_haptic_array_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __obstacle_haptic_array_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__obstacle_haptic_array_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x7b14f4016d8e928eLL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __obstacle_haptic_array_t_get_hash(void)
{
    if (!__obstacle_haptic_array_t_hash_computed) {
        __obstacle_haptic_array_t_hash = (int64_t)__obstacle_haptic_array_t_hash_recursive(NULL);
        __obstacle_haptic_array_t_hash_computed = 1;
    }

    return __obstacle_haptic_array_t_hash;
}

int __obstacle_haptic_array_t_encode_array(void *buf, int offset, int maxlen, const obstacle_haptic_array_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].state_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].has_input), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].see_ground), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ground_height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ground_height_std), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].trans_xyzrpy, 6);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_ranges), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges_state, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges_m, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges_ir_valid, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges_m_ir, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges_m_dense, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges_m_hit, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_traj), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges_trajlib_hit, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].obj_ids, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].tts_data), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].bbox_rgb_xs, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].bbox_rgb_ys, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].bbox_rgb_ws, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].bbox_rgb_hs, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].bbox_d_xs, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].bbox_d_ys, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].bbox_d_ws, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].bbox_d_hs, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].h_min_r), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].h_max_r), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].h_pattern_setting), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].intensities, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].frequencies, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].states, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int obstacle_haptic_array_t_encode(void *buf, int offset, int maxlen, const obstacle_haptic_array_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __obstacle_haptic_array_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __obstacle_haptic_array_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __obstacle_haptic_array_t_encoded_array_size(const obstacle_haptic_array_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __int32_t_encoded_array_size(&(p[element].state_id), 1);

        size += __int16_t_encoded_array_size(&(p[element].has_input), 1);

        size += __int16_t_encoded_array_size(&(p[element].see_ground), 1);

        size += __double_encoded_array_size(&(p[element].ground_height), 1);

        size += __double_encoded_array_size(&(p[element].ground_height_std), 1);

        size += __double_encoded_array_size(p[element].trans_xyzrpy, 6);

        size += __int32_t_encoded_array_size(&(p[element].num_ranges), 1);

        size += __int16_t_encoded_array_size(p[element].ranges_state, p[element].num_ranges);

        size += __double_encoded_array_size(p[element].ranges_m, p[element].num_ranges);

        size += __double_encoded_array_size(p[element].ranges_ir_valid, p[element].num_ranges);

        size += __double_encoded_array_size(p[element].ranges_m_ir, p[element].num_ranges);

        size += __double_encoded_array_size(p[element].ranges_m_dense, p[element].num_ranges);

        size += __double_encoded_array_size(p[element].ranges_m_hit, p[element].num_ranges);

        size += __int16_t_encoded_array_size(&(p[element].num_traj), 1);

        size += __int16_t_encoded_array_size(p[element].ranges_trajlib_hit, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].obj_ids, p[element].num_ranges);

        size += __string_encoded_array_size(&(p[element].tts_data), 1);

        size += __int16_t_encoded_array_size(p[element].bbox_rgb_xs, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].bbox_rgb_ys, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].bbox_rgb_ws, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].bbox_rgb_hs, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].bbox_d_xs, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].bbox_d_ys, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].bbox_d_ws, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].bbox_d_hs, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].ranges, p[element].num_ranges);

        size += __double_encoded_array_size(&(p[element].h_min_r), 1);

        size += __double_encoded_array_size(&(p[element].h_max_r), 1);

        size += __int16_t_encoded_array_size(&(p[element].h_pattern_setting), 1);

        size += __int16_t_encoded_array_size(p[element].intensities, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].frequencies, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].states, p[element].num_ranges);

    }
    return size;
}

int obstacle_haptic_array_t_encoded_size(const obstacle_haptic_array_t *p)
{
    return 8 + __obstacle_haptic_array_t_encoded_array_size(p, 1);
}

int __obstacle_haptic_array_t_decode_array(const void *buf, int offset, int maxlen, obstacle_haptic_array_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].state_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].has_input), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].see_ground), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ground_height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ground_height_std), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].trans_xyzrpy, 6);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_ranges), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ranges_state = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges_state, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ranges_m = (double*) lcm_malloc(sizeof(double) * p[element].num_ranges);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges_m, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ranges_ir_valid = (double*) lcm_malloc(sizeof(double) * p[element].num_ranges);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges_ir_valid, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ranges_m_ir = (double*) lcm_malloc(sizeof(double) * p[element].num_ranges);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges_m_ir, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ranges_m_dense = (double*) lcm_malloc(sizeof(double) * p[element].num_ranges);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges_m_dense, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ranges_m_hit = (double*) lcm_malloc(sizeof(double) * p[element].num_ranges);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges_m_hit, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_traj), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ranges_trajlib_hit = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges_trajlib_hit, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].obj_ids = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].obj_ids, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].tts_data), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].bbox_rgb_xs = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].bbox_rgb_xs, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].bbox_rgb_ys = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].bbox_rgb_ys, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].bbox_rgb_ws = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].bbox_rgb_ws, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].bbox_rgb_hs = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].bbox_rgb_hs, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].bbox_d_xs = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].bbox_d_xs, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].bbox_d_ys = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].bbox_d_ys, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].bbox_d_ws = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].bbox_d_ws, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].bbox_d_hs = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].bbox_d_hs, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ranges = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].h_min_r), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].h_max_r), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].h_pattern_setting), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].intensities = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].intensities, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].frequencies = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].frequencies, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].states = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].states, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __obstacle_haptic_array_t_decode_array_cleanup(obstacle_haptic_array_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __int32_t_decode_array_cleanup(&(p[element].state_id), 1);

        __int16_t_decode_array_cleanup(&(p[element].has_input), 1);

        __int16_t_decode_array_cleanup(&(p[element].see_ground), 1);

        __double_decode_array_cleanup(&(p[element].ground_height), 1);

        __double_decode_array_cleanup(&(p[element].ground_height_std), 1);

        __double_decode_array_cleanup(p[element].trans_xyzrpy, 6);

        __int32_t_decode_array_cleanup(&(p[element].num_ranges), 1);

        __int16_t_decode_array_cleanup(p[element].ranges_state, p[element].num_ranges);
        if (p[element].ranges_state) free(p[element].ranges_state);

        __double_decode_array_cleanup(p[element].ranges_m, p[element].num_ranges);
        if (p[element].ranges_m) free(p[element].ranges_m);

        __double_decode_array_cleanup(p[element].ranges_ir_valid, p[element].num_ranges);
        if (p[element].ranges_ir_valid) free(p[element].ranges_ir_valid);

        __double_decode_array_cleanup(p[element].ranges_m_ir, p[element].num_ranges);
        if (p[element].ranges_m_ir) free(p[element].ranges_m_ir);

        __double_decode_array_cleanup(p[element].ranges_m_dense, p[element].num_ranges);
        if (p[element].ranges_m_dense) free(p[element].ranges_m_dense);

        __double_decode_array_cleanup(p[element].ranges_m_hit, p[element].num_ranges);
        if (p[element].ranges_m_hit) free(p[element].ranges_m_hit);

        __int16_t_decode_array_cleanup(&(p[element].num_traj), 1);

        __int16_t_decode_array_cleanup(p[element].ranges_trajlib_hit, p[element].num_ranges);
        if (p[element].ranges_trajlib_hit) free(p[element].ranges_trajlib_hit);

        __int16_t_decode_array_cleanup(p[element].obj_ids, p[element].num_ranges);
        if (p[element].obj_ids) free(p[element].obj_ids);

        __string_decode_array_cleanup(&(p[element].tts_data), 1);

        __int16_t_decode_array_cleanup(p[element].bbox_rgb_xs, p[element].num_ranges);
        if (p[element].bbox_rgb_xs) free(p[element].bbox_rgb_xs);

        __int16_t_decode_array_cleanup(p[element].bbox_rgb_ys, p[element].num_ranges);
        if (p[element].bbox_rgb_ys) free(p[element].bbox_rgb_ys);

        __int16_t_decode_array_cleanup(p[element].bbox_rgb_ws, p[element].num_ranges);
        if (p[element].bbox_rgb_ws) free(p[element].bbox_rgb_ws);

        __int16_t_decode_array_cleanup(p[element].bbox_rgb_hs, p[element].num_ranges);
        if (p[element].bbox_rgb_hs) free(p[element].bbox_rgb_hs);

        __int16_t_decode_array_cleanup(p[element].bbox_d_xs, p[element].num_ranges);
        if (p[element].bbox_d_xs) free(p[element].bbox_d_xs);

        __int16_t_decode_array_cleanup(p[element].bbox_d_ys, p[element].num_ranges);
        if (p[element].bbox_d_ys) free(p[element].bbox_d_ys);

        __int16_t_decode_array_cleanup(p[element].bbox_d_ws, p[element].num_ranges);
        if (p[element].bbox_d_ws) free(p[element].bbox_d_ws);

        __int16_t_decode_array_cleanup(p[element].bbox_d_hs, p[element].num_ranges);
        if (p[element].bbox_d_hs) free(p[element].bbox_d_hs);

        __int16_t_decode_array_cleanup(p[element].ranges, p[element].num_ranges);
        if (p[element].ranges) free(p[element].ranges);

        __double_decode_array_cleanup(&(p[element].h_min_r), 1);

        __double_decode_array_cleanup(&(p[element].h_max_r), 1);

        __int16_t_decode_array_cleanup(&(p[element].h_pattern_setting), 1);

        __int16_t_decode_array_cleanup(p[element].intensities, p[element].num_ranges);
        if (p[element].intensities) free(p[element].intensities);

        __int16_t_decode_array_cleanup(p[element].frequencies, p[element].num_ranges);
        if (p[element].frequencies) free(p[element].frequencies);

        __int16_t_decode_array_cleanup(p[element].states, p[element].num_ranges);
        if (p[element].states) free(p[element].states);

    }
    return 0;
}

int obstacle_haptic_array_t_decode(const void *buf, int offset, int maxlen, obstacle_haptic_array_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __obstacle_haptic_array_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __obstacle_haptic_array_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int obstacle_haptic_array_t_decode_cleanup(obstacle_haptic_array_t *p)
{
    return __obstacle_haptic_array_t_decode_array_cleanup(p, 1);
}

int __obstacle_haptic_array_t_clone_array(const obstacle_haptic_array_t *p, obstacle_haptic_array_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __int32_t_clone_array(&(p[element].state_id), &(q[element].state_id), 1);

        __int16_t_clone_array(&(p[element].has_input), &(q[element].has_input), 1);

        __int16_t_clone_array(&(p[element].see_ground), &(q[element].see_ground), 1);

        __double_clone_array(&(p[element].ground_height), &(q[element].ground_height), 1);

        __double_clone_array(&(p[element].ground_height_std), &(q[element].ground_height_std), 1);

        __double_clone_array(p[element].trans_xyzrpy, q[element].trans_xyzrpy, 6);

        __int32_t_clone_array(&(p[element].num_ranges), &(q[element].num_ranges), 1);

        q[element].ranges_state = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].ranges_state, q[element].ranges_state, p[element].num_ranges);

        q[element].ranges_m = (double*) lcm_malloc(sizeof(double) * q[element].num_ranges);
        __double_clone_array(p[element].ranges_m, q[element].ranges_m, p[element].num_ranges);

        q[element].ranges_ir_valid = (double*) lcm_malloc(sizeof(double) * q[element].num_ranges);
        __double_clone_array(p[element].ranges_ir_valid, q[element].ranges_ir_valid, p[element].num_ranges);

        q[element].ranges_m_ir = (double*) lcm_malloc(sizeof(double) * q[element].num_ranges);
        __double_clone_array(p[element].ranges_m_ir, q[element].ranges_m_ir, p[element].num_ranges);

        q[element].ranges_m_dense = (double*) lcm_malloc(sizeof(double) * q[element].num_ranges);
        __double_clone_array(p[element].ranges_m_dense, q[element].ranges_m_dense, p[element].num_ranges);

        q[element].ranges_m_hit = (double*) lcm_malloc(sizeof(double) * q[element].num_ranges);
        __double_clone_array(p[element].ranges_m_hit, q[element].ranges_m_hit, p[element].num_ranges);

        __int16_t_clone_array(&(p[element].num_traj), &(q[element].num_traj), 1);

        q[element].ranges_trajlib_hit = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].ranges_trajlib_hit, q[element].ranges_trajlib_hit, p[element].num_ranges);

        q[element].obj_ids = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].obj_ids, q[element].obj_ids, p[element].num_ranges);

        __string_clone_array(&(p[element].tts_data), &(q[element].tts_data), 1);

        q[element].bbox_rgb_xs = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].bbox_rgb_xs, q[element].bbox_rgb_xs, p[element].num_ranges);

        q[element].bbox_rgb_ys = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].bbox_rgb_ys, q[element].bbox_rgb_ys, p[element].num_ranges);

        q[element].bbox_rgb_ws = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].bbox_rgb_ws, q[element].bbox_rgb_ws, p[element].num_ranges);

        q[element].bbox_rgb_hs = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].bbox_rgb_hs, q[element].bbox_rgb_hs, p[element].num_ranges);

        q[element].bbox_d_xs = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].bbox_d_xs, q[element].bbox_d_xs, p[element].num_ranges);

        q[element].bbox_d_ys = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].bbox_d_ys, q[element].bbox_d_ys, p[element].num_ranges);

        q[element].bbox_d_ws = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].bbox_d_ws, q[element].bbox_d_ws, p[element].num_ranges);

        q[element].bbox_d_hs = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].bbox_d_hs, q[element].bbox_d_hs, p[element].num_ranges);

        q[element].ranges = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].ranges, q[element].ranges, p[element].num_ranges);

        __double_clone_array(&(p[element].h_min_r), &(q[element].h_min_r), 1);

        __double_clone_array(&(p[element].h_max_r), &(q[element].h_max_r), 1);

        __int16_t_clone_array(&(p[element].h_pattern_setting), &(q[element].h_pattern_setting), 1);

        q[element].intensities = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].intensities, q[element].intensities, p[element].num_ranges);

        q[element].frequencies = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].frequencies, q[element].frequencies, p[element].num_ranges);

        q[element].states = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].states, q[element].states, p[element].num_ranges);

    }
    return 0;
}

obstacle_haptic_array_t *obstacle_haptic_array_t_copy(const obstacle_haptic_array_t *p)
{
    obstacle_haptic_array_t *q = (obstacle_haptic_array_t*) malloc(sizeof(obstacle_haptic_array_t));
    __obstacle_haptic_array_t_clone_array(p, q, 1);
    return q;
}

void obstacle_haptic_array_t_destroy(obstacle_haptic_array_t *p)
{
    __obstacle_haptic_array_t_decode_array_cleanup(p, 1);
    free(p);
}

int obstacle_haptic_array_t_publish(lcm_t *lc, const char *channel, const obstacle_haptic_array_t *p)
{
      int max_data_size = obstacle_haptic_array_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = obstacle_haptic_array_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _obstacle_haptic_array_t_subscription_t {
    obstacle_haptic_array_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void obstacle_haptic_array_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    obstacle_haptic_array_t p;
    memset(&p, 0, sizeof(obstacle_haptic_array_t));
    status = obstacle_haptic_array_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding obstacle_haptic_array_t!!!\n", status);
        return;
    }

    obstacle_haptic_array_t_subscription_t *h = (obstacle_haptic_array_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    obstacle_haptic_array_t_decode_cleanup (&p);
}

obstacle_haptic_array_t_subscription_t* obstacle_haptic_array_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    obstacle_haptic_array_t_handler_t f, void *userdata)
{
    obstacle_haptic_array_t_subscription_t *n = (obstacle_haptic_array_t_subscription_t*)
                       malloc(sizeof(obstacle_haptic_array_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 obstacle_haptic_array_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg obstacle_haptic_array_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int obstacle_haptic_array_t_subscription_set_queue_capacity (obstacle_haptic_array_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int obstacle_haptic_array_t_unsubscribe(lcm_t *lcm, obstacle_haptic_array_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe obstacle_haptic_array_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

